language: php
php:
    - 7.0
    - 7.1

script:
    - composer build

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: flase
